
function add(a, b)
	return a+b
end

SERVER_TYPE_LOGON = 0
SERVER_TYPE_KEEPER = 1
SERVER_TYPE_FORWARD = 2
SERVER_TYPE_DB = 3
SERVER_TYPE_GAME = 4

SERVER_ID_LOGON = 10001
SERVER_ID_KEEPER = 10011
SERVER_ID_FORWARD_1 = 10021
SERVER_ID_FORWARD_2 = 10022
SERVER_ID_FORWARD_3 = 10023
SERVER_ID_DB = 10031
SERVER_ID_GAME = 10041

SERVER_IP = "127.0.0.1"

serversConfig = {
	[SERVER_ID_KEEPER] = {ttype=SERVER_TYPE_KEEPER, ip=SERVER_IP, port=SERVER_ID_KEEPER},
	[SERVER_ID_FORWARD_1] = {ttype=SERVER_TYPE_FORWARD, ip=SERVER_IP, port=SERVER_ID_FORWARD_1},
	[SERVER_ID_FORWARD_2] = {ttype=SERVER_TYPE_FORWARD, ip=SERVER_IP, port=SERVER_ID_FORWARD_2},
	[SERVER_ID_FORWARD_3] = {ttype=SERVER_TYPE_FORWARD, ip=SERVER_IP, port=SERVER_ID_FORWARD_3},
	[SERVER_ID_DB] = {ttype=SERVER_TYPE_DB, ip=SERVER_IP, port=SERVER_ID_DB},
	[SERVER_ID_GAME] = {ttype=SERVER_TYPE_GAME, ip=SERVER_IP, port=SERVER_ID_DB},
}

function getKeeperServerConfig()
	return serversConfig[SERVER_ID_KEEPER]
end

