FIND_PATH(MYSQLPP_INCLUDE_DIR mysql++.h 
	/usr/include/mysql++
	/usr/local/include/mysql++)

FIND_LIBRARY(MYSQLPP_LIBRARY mysqlpp)

IF (MYSQLPP_INCLUDE_DIR AND MYSQLPP_LIBRARY)
	SET(MYSQLPP_FOUND TRUE)

	INCLUDE_DIRECTORIES(${MYSQLPP_INCLUDE_DIR})
	LINK_DIRECTORIES(${MYSQLPP_LIBRARY})

	MESSAGE(STATUS "MySQL++ Include dir: ${MYSQLPP_INCLUDE_DIR}  library dir: ${MYSQLPP_LIBRARY}")

ELSE (MYSQLPP_INCLUDE_DIR AND MYSQLPP_LIBRARY)
	SET(MYSQLPP_FOUND FALSE)
	MESSAGE(FATAL_ERROR "Cannot find MySQL++. Include dir: ${MYSQLPP_INCLUDE_DIR}  library dir: ${MYSQLPP_LIBRARY}")
ENDIF (MYSQLPP_INCLUDE_DIR AND MYSQLPP_LIBRARY)



MARK_AS_ADVANCED(MYSQLPP_LIBRARY MYSQLPP_INCLUDE_DIR)

