#ifndef MUDUO_NET_SERVER_TYPE_H
#define MUDUO_NET_SERVER_TYPE_H


namespace muduo
{
namespace net
{
enum ServerType
{
  SERVER_TYPE_LOGON = 1,
  SERVER_TYPE_KEEPER = 2,
  SERVER_TYPE_FORWARD = 3,
  SERVER_TYPE_DB = 4,
  SERVER_TYPE_GAME = 5
};

enum ServerID
{
  SERVER_ID_LOGON = 10001,
  SERVER_ID_KEEPER = 10011,
  SERVER_ID_FORWARD_1 = 10021,
  SERVER_ID_FORWARD_2 = 10022,
  SERVER_ID_FORWARD_3 = 10023,
  SERVER_ID_DB = 10031,
  SERVER_ID_GAME = 10041
};
}
}

#endif  // MUDUO_NET_SERVER_TYPE_H
